name: ecommerce_app
description: "Trabalho final POO II"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.6
  get_it: ^7.6.7
  responsive_framework: 1.1.1
  connectivity_plus: ^6.0.1
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env